[2022-06-05 00:39:17,605] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: census.populate_table scheduled__2022-06-05T01:28:06.051317+00:00 [queued]>
[2022-06-05 00:39:17,678] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: census.populate_table scheduled__2022-06-05T01:28:06.051317+00:00 [queued]>
[2022-06-05 00:39:17,679] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-05 00:39:17,679] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-05 00:39:17,679] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-05 00:39:17,720] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): populate_table> on 2022-06-05 01:28:06.051317+00:00
[2022-06-05 00:39:17,747] {standard_task_runner.py:52} INFO - Started process 25599 to run task
[2022-06-05 00:39:17,763] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'census', 'populate_table', 'scheduled__2022-06-05T01:28:06.051317+00:00', '--job-id', '661', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpl6liyb96', '--error-file', '/tmp/tmpwl8vx4t5']
[2022-06-05 00:39:17,764] {standard_task_runner.py:80} INFO - Job 661: Subtask populate_table
[2022-06-05 00:39:18,020] {task_command.py:370} INFO - Running <TaskInstance: census.populate_table scheduled__2022-06-05T01:28:06.051317+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-06-05 00:39:18,273] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=census
AIRFLOW_CTX_TASK_ID=populate_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T01:28:06.051317+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T01:28:06.051317+00:00
[2022-06-05 00:39:18,284] {logging_mixin.py:115} INFO - <_io.TextIOWrapper name='teste_uiliam.csv' mode='r' encoding='UTF-8'>
[2022-06-05 00:39:18,674] {python.py:173} INFO - Done. Returned value was: None
[2022-06-05 00:39:18,939] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=census, task_id=populate_table, execution_date=20220605T012806, start_date=20220605T033917, end_date=20220605T033918
[2022-06-05 00:39:19,066] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-05 00:39:19,212] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
