[2022-06-17 17:11:59,950] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: sales.create_tables_tasks.criar_Stage_Customers scheduled__2022-06-17T20:11:30.740117+00:00 [queued]>
[2022-06-17 17:11:59,998] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: sales.create_tables_tasks.criar_Stage_Customers scheduled__2022-06-17T20:11:30.740117+00:00 [queued]>
[2022-06-17 17:11:59,998] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 17:11:59,998] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-17 17:11:59,998] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 17:12:00,074] {taskinstance.py:1378} INFO - Executing <Task(PostgresOperator): create_tables_tasks.criar_Stage_Customers> on 2022-06-17 20:11:30.740117+00:00
[2022-06-17 17:12:00,095] {standard_task_runner.py:52} INFO - Started process 133300 to run task
[2022-06-17 17:12:00,113] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales', 'create_tables_tasks.criar_Stage_Customers', 'scheduled__2022-06-17T20:11:30.740117+00:00', '--job-id', '1242', '--raw', '--subdir', 'DAGS_FOLDER/dag copy.py', '--cfg-path', '/tmp/tmp1wqrg0tt', '--error-file', '/tmp/tmpdfe4rof0']
[2022-06-17 17:12:00,113] {standard_task_runner.py:80} INFO - Job 1242: Subtask create_tables_tasks.criar_Stage_Customers
[2022-06-17 17:12:00,353] {task_command.py:370} INFO - Running <TaskInstance: sales.create_tables_tasks.criar_Stage_Customers scheduled__2022-06-17T20:11:30.740117+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-06-17 17:12:00,715] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=sales
AIRFLOW_CTX_TASK_ID=create_tables_tasks.criar_Stage_Customers
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T20:11:30.740117+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T20:11:30.740117+00:00
[2022-06-17 17:12:00,766] {base.py:68} INFO - Using connection ID '***_default' for task execution.
[2022-06-17 17:12:00,787] {dbapi.py:213} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS Stg_Customers (
                customername VARCHAR(30),
                contactlastname VARCHAR(30),
                contactfirstname VARCHAR(30),
                phone VARCHAR(30),
                addressline1 VARCHAR(30),
                city VARCHAR(30),
                state VARCHAR(20),
                postalcode VARCHAR(30),
                country VARCHAR(30),
                creditlimit FLOAT
                )
            , parameters: None
[2022-06-17 17:12:00,866] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=sales, task_id=create_tables_tasks.criar_Stage_Customers, execution_date=20220617T201130, start_date=20220617T201159, end_date=20220617T201200
[2022-06-17 17:12:00,971] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-17 17:12:01,137] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
