[2022-06-17 17:12:00,876] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: sales.create_tables_tasks.criar_Stage_Employees scheduled__2022-06-17T20:11:43.712679+00:00 [queued]>
[2022-06-17 17:12:00,917] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: sales.create_tables_tasks.criar_Stage_Employees scheduled__2022-06-17T20:11:43.712679+00:00 [queued]>
[2022-06-17 17:12:00,918] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 17:12:00,919] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-17 17:12:00,922] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 17:12:01,012] {taskinstance.py:1378} INFO - Executing <Task(PostgresOperator): create_tables_tasks.criar_Stage_Employees> on 2022-06-17 20:11:43.712679+00:00
[2022-06-17 17:12:01,033] {standard_task_runner.py:52} INFO - Started process 133417 to run task
[2022-06-17 17:12:01,058] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales', 'create_tables_tasks.criar_Stage_Employees', 'scheduled__2022-06-17T20:11:43.712679+00:00', '--job-id', '1245', '--raw', '--subdir', 'DAGS_FOLDER/dag copy.py', '--cfg-path', '/tmp/tmp7mpnt3fp', '--error-file', '/tmp/tmp45nikgv_']
[2022-06-17 17:12:01,059] {standard_task_runner.py:80} INFO - Job 1245: Subtask create_tables_tasks.criar_Stage_Employees
[2022-06-17 17:12:01,208] {task_command.py:370} INFO - Running <TaskInstance: sales.create_tables_tasks.criar_Stage_Employees scheduled__2022-06-17T20:11:43.712679+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-06-17 17:12:01,405] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=sales
AIRFLOW_CTX_TASK_ID=create_tables_tasks.criar_Stage_Employees
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T20:11:43.712679+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T20:11:43.712679+00:00
[2022-06-17 17:12:01,428] {base.py:68} INFO - Using connection ID '***_default' for task execution.
[2022-06-17 17:12:01,435] {dbapi.py:213} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS Stg_Emp (
                lastname VARCHAR(30),
                firstname VARCHAR(30),
                email VARCHAR (40),
                jobtitle VARCHAR(30)
                )
            , parameters: None
[2022-06-17 17:12:01,437] {postgres.py:94} INFO - NOTICE:  relation "stg_emp" already exists, skipping

[2022-06-17 17:12:01,465] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=sales, task_id=create_tables_tasks.criar_Stage_Employees, execution_date=20220617T201143, start_date=20220617T201200, end_date=20220617T201201
[2022-06-17 17:12:01,519] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-17 17:12:01,597] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
