[2022-06-06 15:14:02,238] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: census.populate_table scheduled__2022-06-06T18:13:44.469509+00:00 [queued]>
[2022-06-06 15:14:02,254] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: census.populate_table scheduled__2022-06-06T18:13:44.469509+00:00 [queued]>
[2022-06-06 15:14:02,255] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 15:14:02,255] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-06 15:14:02,255] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 15:14:02,275] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): populate_table> on 2022-06-06 18:13:44.469509+00:00
[2022-06-06 15:14:02,284] {standard_task_runner.py:52} INFO - Started process 17384 to run task
[2022-06-06 15:14:02,291] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'census', 'populate_table', 'scheduled__2022-06-06T18:13:44.469509+00:00', '--job-id', '1228', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2kyexot0', '--error-file', '/tmp/tmpn4nz13og']
[2022-06-06 15:14:02,292] {standard_task_runner.py:80} INFO - Job 1228: Subtask populate_table
[2022-06-06 15:14:02,386] {task_command.py:370} INFO - Running <TaskInstance: census.populate_table scheduled__2022-06-06T18:13:44.469509+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-06-06 15:14:02,494] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=census
AIRFLOW_CTX_TASK_ID=populate_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T18:13:44.469509+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T18:13:44.469509+00:00
[2022-06-06 15:14:03,226] {python.py:173} INFO - Done. Returned value was: 1630
[2022-06-06 15:14:03,251] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=census, task_id=populate_table, execution_date=20220606T181344, start_date=20220606T181402, end_date=20220606T181403
[2022-06-06 15:14:03,304] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-06 15:14:03,360] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
